services: mongodb
language: ruby
script: "bundle exec rake spec"
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0
env:
  - CODECLIMATE_REPO_TOKEN=08c4925d2cd6a7ca5603cc761ec6c7df4104b98321704a4f512700b2cb4a2f57
gemfile:
  - gemfiles/active_record_32.gemfile
  - gemfiles/active_record_40.gemfile
  - gemfiles/active_record_41.gemfile
  - gemfiles/active_record_42.gemfile
notifications:
  email: false
addons:
  code_climate:
    repo_token: 08c4925d2cd6a7ca5603cc761ec6c7df4104b98321704a4f512700b2cb4a2f57